### PR TITLE
blackify

### PR DESCRIPTION
**Pull request by catlee**
blackified all the code, and added a check to ensure the code formatting stays consistent.

Moved all the test code and data out of signingscript/test and into a tests/ directory. I also changed how fixtures are getting imported, and removed our custom tmpdir fixture.

Moved all of the application code from signingscript into src/signingscript

There should be no functional differences.

### CODE REVIEW

**Comment by escapewindow** [comment]
Hm. Any reason we didn't do `black` as its own PR? This is doable, but it'll be a more in-depth review.

**Comment by catlee** [comment]
> Hm. Any reason we didn't do `black` as its own PR? This is doable, but it'll be a more in-depth review.

Sure. I've split out the other patches into another branch. Will submit a PR after.

**Comment by escapewindow** [comment]
Hm, I'm getting a big diff when I run `black .` in `signingscript/.` (toplevel) on revision `bfebb0b4e8dc54de644aed785ac938cabbcf45ad` and diffing it against your PR?

**Comment by catlee** [comment]
I excluded the vendor library. Maybe that's it?

**Comment by escapewindow** [comment]
I don't think so? [diff](https://gist.github.com/escapewindow/1fb23224da9714511f6bb81777f0e5df)

**Pull request merged**
