### PR TITLE
Strip existing APK signature

### LINKED ISSUE #82: signingscript should strip META-INF/ from apks before signing
We may want to preserve this in some cases, so we may want to add a flag. For now, stripping it before sending for signing in all cases should be fine.

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Fixes #82

Depends on #85

### CODE REVIEW

**Comment by escapewindow** [comment]
@JohanLorenzo the travis bustage is due to #80; we should fix up #85 to green.

**Comment by JohanLorenzo** [comment]
Oh that's right! I should have thought of it yesterday. Then, the PR is fixed. I'm okay to close it in favor of #83 if this approach makes more sense.

**Comment by JohanLorenzo** [comment]
It worked with the latest nightly on https://queue.taskcluster.net/v1/task/ARmkAT3pTx-UcvrNdGF6Jg/runs/0/artifacts/public/app-focus-arm-nightly-unsigned.apk. (I pinned the worker to my end). 

Landing the PR.

**Comment by JohanLorenzo** [comment]
This was deployed and used by Focus after https://github.com/mozilla-releng/build-puppet/pull/280 landed.

**Pull request merged**
